### ISSUE TITLE
Integration Tests missing a call to setMockClock()

### ISSUE THREAD

**Issue by adamlsmith** [bitcoin-solutions/multibit#631]
In order to build from source, I had to add a call to setMockClock() as the first statement in the method transactionsList() in /test/java/com/google/bitcoin/core/WalletTest.java

Otherwise the integration tests fail with:

Tests in error: 
  transactionsList(com.google.bitcoin.core.WalletTest): You need to use setMockClock() first.
  keyCreationTime(com.google.bitcoin.core.WalletTest): You need to use setMockClock() first.
  scriptCreationTime(com.google.bitcoin.core.WalletTest): You need to use setMockClock() first.
  keyRotation(com.google.bitcoin.core.WalletTest): You need to use setMockClock() first.

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .

**Comment by rogueSnake** [comment]
I also had this issue, and in addition to adding 
        setMockClock(); 
to the beginning of transactionsList (line 922) I also had to put it at the top of keyRotation (line 2134).  Still running into other build problems, but that got the tests to pass without any errors.

**Comment by gary-rowe** [comment]
Bumping this in 0.5.19 to verify it against Travis after MultiBit Classic repo is moved under Bitcoin Solutions.

Marking as "awaiting issue" accordingly.

**Comment by gary-rowe** [comment]
Pushed a fix to ensure Travis builds OK.

Ready for review and close.

**Comment by gary-rowe** [comment]
Travis builds OK so closing.
