### ISSUE TITLE
Mac application doesn't include version number

### ISSUE THREAD

**Issue by sgrimm** [bitcoin-solutions/multibit#688]
Bug report
  Operating System: OS X 10.10.3
  MultiBit Version: 0.5.18
  Steps to replicate the problem: Select the MultiBit application in a Finder window and hit command-i or the File > Get Info menu item to bring up the information dialog. The "Version" field is missing; in the dialog it has a value of "--" rather than a version number.

The lack of version number prevents application management tools such as AppFresh from automatically detecting that the application is out of date when a new version is released.

**Comment by gary-rowe** [comment]
Thanks for reporting this. We're planning a 0.5.19 maintenance release of MultiBit Classic after we've released [MultiBit HD](https://beta.multibit.org) so we'll fix it then.

**Comment by jim618** [comment]
This is now included (as a result of us switching to the Install4j installer).

Awaiting review and closing

**Comment by gary-rowe** [comment]
Install4j verified as providing version on OS X. 

Closing.
