### ISSUE TITLE
Incorrect password

### ISSUE THREAD

**Issue by sebastiaan321** [bitcoin-solutions/multibit#690]
When I try to send bitcoins from my wallet and enter the password it says "The wallet password is incorrect". When removing the password from the wallet I get "Could not decrypt bytes".

I'm pretty sure I have the correct password, also when running this on the command line it returns successfully:

```openssl enc -d -p -aes-256-cbc -a -in mywallet.key -out restored.key -pass pass:mypassword```

Do I have to do something with the restored key? How can it be possible that the application cannot decrypt the wallet while the command line can?

**Comment by gary-rowe** [comment]
Can I clarify that you are able to unlock your wallet from the command line, but MultiBit fails to unlock it?

**Comment by sebastiaan321** [comment]
correct

**Comment by gary-rowe** [comment]
On closer reading of your original statement, it appears that you've got one password for your wallet and a different one that was used when exporting the private key(s). You could, for example, import those keys back into a new, empty wallet with a fresh password and restore all funds associated with them.

If you don't have a working password for a wallet then you may find this article useful: https://multibit.org/en/help/v0.5/help_lostOrForgottenPassword.html. We cannot help you to recover from a lost password, but if you know roughly what it was then there are wallet recovery services that may be able to help.

**Comment by sebastiaan321** [comment]
Thank you for your advice. I may have changed the password for the wallet in the past, it was a long time ago. How does this transferring to new wallet work? I have tried the following without success:

- Created a new wallet (no password)
- Import private keys, chose the key from the key-backup directory of the wallet with the BTC
- Enter the password for the import file (which is correct according openssl cmd)
- Unlock
- Import private keys

This gives me the error: "The private keys unlock failed. The error was 'Could not understand address in import file'"

Next I tried to use the output key of the openssl cmd, then the password for import file box grays out but import private keys results in the same error. I'm I doing something wrong? Did past multibit updates not update my keys correctly? or ..

**Comment by gary-rowe** [comment]
If your `.key` is decrypting correctly then it should import fine. It may be that during your `openssl` operations you've modified the underlying file. 

Have a read of this article that describes the export private key file format and verify that your contents follow the same format: https://multibit.org/en/help/v0.5/help_exportingPrivateKeys.html

**Comment by jim618** [comment]
Adding to Gary's note, one thing you can also try is to validate that each private key in the file is correct and matches a receiving address.

You can do this by making an offline copy of https://bitaddress.org 
(Do a File | Save in your browser and use the local copy).

Then, once you have got past the 'create random number' bit click in the header on the Wallet Details tab.
You can then enter the private key and see the corresponding address. The address should be listed in your receiving addresses.  It could be that one of the private keys has a problem (for whatever reason) but that would mean you could still import all the rest.

Just to be crystal clear: DO NOT POST ANY PRIVATE KEY HERE
I am sure you know not to do this but I just wanted to repeat it.

**Comment by sebastiaan321** [comment]
Thank you for the help, I really appreciate it. I had a look at the format of .key file and it looks like a password protected private key as described on the page suggested by Gary but I wonder if I'm looking at the right key file. For my understanding, what is the function of the key in wallet-data/key-backup directory, isn't this the private key? Is it different from the exported private key? And how does it relate to the wallet password?

I'm not sure if I even made an export of the private keys before and if I try to make one I need the password for that wallet which I don't remember exactly. Is there a way I can try to find the wallet password like I did for the private key using a script as described on the lost or forgotten password page?

Further more I tried the suggestion of Jim, the offline page did not accept the content of the key file but when using the key value given by the openssl output it does accept it and gives a bitcoin address but it isn't mine.

**Comment by gary-rowe** [comment]
Apologies for the slow response here. Were you able to resolve this in the end?

**Comment by sebastiaan321** [comment]
No unfortunately I haven't been able to resolve this issue yet and I don't know what to do.

**Comment by sebastiaan321** [comment]
This issue can be closed, I have found my password :-)
The one I found earlier was a false positive. Next I used btcrecover to test more options, it also gave some false positives but in the end the correct one as well.

**Comment by gary-rowe** [comment]
Glad to hear you were able to recover your bitcoins :-)

**Comment by djuuss** [comment]
Hello, i'm having the same issue.

>This gives me the error: "The private keys unlock failed. The error was 'Could not understand address in import file'"

And openssl decryption with the same password i know works gives a garbage output file. Base64 output of this file starts with Salted_

**Comment by Jenova55** [comment]
@djuuss
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : walletsrecoveryservice@gmail.com
