### ISSUE TITLE
Updates Stopped... again.

### ISSUE THREAD

**Issue by Adnaro** [bitcoin-solutions/multibit#693]
Operating System: OS X Version: 10.10.3
 MultiBit Version: 0.5.18

I'm having this problem and I really can't figure it out. I've looked extensively on previous 'issues' and on google, others have had the same problem, but no indication as to how they fixed it. 

Basically, everything worked just fine, couple days ago, Multibit crashes as I'm trying to send. now, every time I load it up it needs to re-sync ALL previous transactions (which takes forever, unsure whether it's a CPU problem or an internet problem, likely the latter as I'm on 300kb/s.). Once it's finished synchronising, anything I do, INCLUDING trying to export my private keys, gives me the error "Another program has changed this wallet" etc. "Updates Stopped". 

- backed up my whole multibit folder
- rebooted (ofc) 
- reinstalled Multibit 
- deleted multibit.spvchain
- 'reset blockchain and transactions'
- checked activity monitor that nothing else is running
- new java 

all I desperately need to do is move all my stuff to Blockchain.info. Any ideas guys?

Thanks in advance,
Alex

**Comment by Adnaro** [comment]
So, I'm still stuck with this issue and was checking back here twice a day to see if it had been looked at. I would have appreciated some sort of acknowledgment, but never mind. 

Have I not provided enough info? I'm actually moving to London in a couple of weeks, is there anyone I could arrange a meeting with to help me fix this? I'd be willing to pay of course. 

Thanks...

**Comment by jim618** [comment]
The 'Updates stopped' message is shown when the timestamp and size of either the wallet file or the wallet info file changes changes unexpectedly. (i.e. Not by the running instance of MultiBit).

One way to sidestep the exact reason it is happening on your machine is to copy the wallet(s) onto a USB stick and install MultiBit on ANOTHER machine and open the wallet on that machine. Then export the private keys so that you can import them into blockchain.info

**Comment by jim618** [comment]
p.s. the wallet format is identical across operating systems so the other machine can be Windows/ Mac/ Linux

**Comment by Adnaro** [comment]
Hi, thanks for the reply.

I tried that using an iMac running Mavericks and another Macbook Pro running Yosemite. Both give me the same response.

Maybe I'm copying the files incorrectly? I've tried moving just the .wallet file as well as moving the whole folder in the library. Am I doing this wrong? Moving the .wallet file didn't work at all, and moving the whole folder gives me the same 'updates stopped' message as on my original laptop.

**Comment by Adnaro** [comment]
Alright, I finally managed to stealthily get it out of there. But this is a pretty serious thing that needs to be fixed in the software. Somehow, between the few seconds of having opened MultiBit and it deciding to synchronise itself, gave me a window of opportunity to export the private keys without it giving me the error message: 'Updates Stopped'. 

So, I guess this needs to be looked into. As a merchant and being relatively new to this technology, it wasn't obvious to me (especially as it's for sure a bug in the software). Anyone less savvy would probably never have figured it out, and I must admit the support here really wasn't fantastic. It's the type of thing hindering the technology. Early days, I know...

**Comment by gary-rowe** [comment]
Glad you managed to get the keys out, and apologies for the slow responses to this issue. Unfortunately we're both maxed out with [MultiBit HD](https://beta.multibit.org) and this is greatly reducing our available time for MultiBit Classic support. This will be changing in the near future once the Release 0.1 is complete and we prepare the 0.5.19 MultiBit Classic maintenance update.

MultiBit HD has fixes for many of the issues present MultiBit Classic and [there is an upgrade path available](https://beta.multibit.org/en/help/hd0.1/how-to-upgrade-from-classic.html).

**Comment by suwenxu** [comment]
Hi, may I request for a simplified to-do-steps for the solution to this issue as I'm facing the "updates stopped" issue too and I don't quite get the steps mentioned above.

**Comment by jim618** [comment]
I think it's best if we remove the timestamp/ filesize checking for 0.5.19.
It was put in originally to detect when users had multiple copies of MultiBit pointing at the same wallet file on a network.
It seems to be creating more problems than it is solving and, especially as MultiBit is now in maintenance mode, I think it would be better to remove the checks.

**Comment by suwenxu** [comment]
Ok thank you very much.

**Comment by jim618** [comment]
The 'updates stopped' functionality has bee removed.
Easiest way to test it is to change the wallet file (say with a paste) or edit the info file.

Awaiting review and closing.

**Comment by suwenxu** [comment]
Okay noted. Thank you very much for your info. =)

**Comment by gary-rowe** [comment]
Code changes look OK. Started a long sync and applied various `touch` commands to the wallet file which had no effect on the sync (it just chugged along regardless). After a while the `touch` changes were overwritten by the wallet save operations.

Closing.

**Comment by jmdarts007** [comment]
Thanks and I am sorry late replay
