### ISSUE TITLE
World-writable executable in MultiBit.app (Mac OS X)

### ISSUE THREAD

**Issue by ChristopherJSanborn** [bitcoin-solutions/multibit#694]
Just installed latest version for OS X (from https://multibit.org/releases/multibit-0.5.18/multibit-0.5.18.dmg).  Permissions on the executable in the .app bundle include world and group write permissions.  Seems this could provide an injection point for malware.
```
-rwxrwxrwx@ 1 sysadmin  admin    72K Apr 28  2014 MultiBit.app/Contents/MacOS/JavaApplicationStub*
````
Seems to me `-rwxr-xr-x` would be a more secure choice.  Can/should this be changed?

**Comment by jim618** [comment]
This is a good idea. I don't think there is any need at all for world and group write access to the exe itself.

**Comment by jim618** [comment]
Also raised in the MultiBit HD issue database here:
https://github.com/bitcoin-solutions/multibit-hd/issues/572

**Comment by jim618** [comment]
Changing over to the Install4j installer now means that the multibit-hd.jar is now read only to world and group.
-rw-r--r--  1 jim  admin  8121539 21 Jul 16:15 multibit-exe.jar

Awaiting review and closing

**Comment by gary-rowe** [comment]
Install4j handles the permissions correctly by default. Closing.
