### ISSUE TITLE
Migrate MultiBit Classic to Bitcoin Solutions

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit#700]
Now that MultiBit HD has replaced MultiBit Classic on the main website we should migrate this repo into Bitcoin Solutions.

This is a simple admin task in GitHub and will preserve the original links through a HTTP redirect so downstream users will not be affected.

**Comment by jim618** [comment]
Waiting for acceptance by user bitcoin-solutions

**Comment by jim618** [comment]
This is now complete.
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working (direct and redirect access). Closing.
