### ISSUE TITLE
Add upgrade banner to inform users about MultiBit HD

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit#701]
Now that MultiBit HD is live we need to assist users with an upgrade from Classic. We should consider a banner with the application to remind them.

**Comment by FredHoek** [comment]
I downloaded Multibit HD but I don't know how to put in my existing wallet from Classic. My Classic was registering with network but does not show the total amount. Could you give me any clues please?

**Comment by jim618** [comment]
@FredHoek  Have a read of:
https://multibit.org/en/help/hd0.1/how-to-upgrade-from-classic.html

**Comment by jim618** [comment]
Added a link to the top right of the MultiBit screen.
The text says: 'Try MultiBit HD'
The tooltip: Visit the MultiBit website to try out MultiBit HD

The text gets an underline if the user mouses over it.
Screen shots to follow.


If System look and feel it appears as unadorned text (best), in other L&F it appears as a button (ok).

Awaiting review and closing

**Comment by jim618** [comment]
Screenshots:

![screen shot 2015-07-23 at 13 14 52](https://cloud.githubusercontent.com/assets/919427/8855087/225da468-315b-11e5-8136-93b40a9170e4.png)

![screen shot 2015-07-23 at 13 14 56](https://cloud.githubusercontent.com/assets/919427/8855089/25980600-315b-11e5-90ba-0ea0f41f9f83.png)

**Comment by gary-rowe** [comment]
As discussed earlier, the text needs to be to the left of the exchange table and float to the right when the exchange table is not present. Due to the number of combinations of LaF within Classic, a simple vertical alignment of "center" will be fine.

**Comment by jim618** [comment]
Swopped round link and ticker:

![screen shot 2015-07-26 at 12 33 20](https://cloud.githubusercontent.com/assets/919427/8893683/b8ccea06-3392-11e5-8440-3420b24c6a67.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.

**Comment by jim618** [comment]
Reopened - I've changed the font to be the UI font so needs rechecking.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working across all screens.

Closing.

**Comment by yegortimoshenko** [comment]
@gary-rowe @jim618 Could you reconsider or at least add a preference to turn this message off? I do know that MultiBit HD is out but I consider it to be unusably ugly. This message is so annoying that I don't update past 0.15.18.

**Comment by jim618** [comment]
Sorry you find it ugly.

We feel now that people really should be moving off Classic and moving to a fully deterministic wallet.
Obviously we want people to upgrade to MultiBit HD but there are plenty of alternatives. 

It's a bit of a nag true, but we have found that even though MultiBit HD has been out for 4 months now we are still seeing a 60 : 40 split of usage with Classic the 60%.
