### ISSUE TITLE
Backport fee slider from MBHD

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit#710]
The fixed fee of 0.0001 mBTC / KB needs to be more flexible in the light of recent network spam attacks.

Backport the fee slider form MBHD 0.1.2 to Classic

**Comment by jim618** [comment]
To do:
+ roundtrip feePerKB in multibit.properties in test
+ check for 'lower than low' + 'higher than high' to avoid hand editing
+ backport feeSlider from MBHD, including localisation where done. Appears on Preferences.
+ fee slider set, change, get
+ check localisation independent - always store with either dot decimal separator or satoshi
+ update send to use normalised property - uses default at the moment

**Comment by gary-rowe** [comment]
Verified working.

Closing.

**Comment by jim618** [comment]
I've reopened this as I have changed the background color and put on an empty border to make the fee slider look better on Windows / different themes.

Awaiting review, retesting and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
