### ISSUE TITLE
Test installer upgrade path for 0.5.19

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit#717]
We need to check that the upgrade path from 0.5.19 to 0.5.20 works ok.

As noone is using 0.5.19 yet we can simply create a '0.5.20' installer and put the upgrades.xml on the multibit.org server to check it works

**Comment by jim618** [comment]
I have created installers of the current develop code that point to the multibit updates-test.xml on the multibit.org server and uploaded them to:

https://www.multibit.org/releases/multibit-classic/multibit-0.0.0/

You can test the auto-update path is working by installing any of these - their version is set to 0.5.19 internally. The updates-test.xml points to 0.5.20 and so you get a "There is an update' message at start up.
There are no 0.5.20 binaries on multibit.org (as it will confuse people) so there is no new installer to actually download but other than that it exercises the while update path.

I have tested the Mac one only IRL.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
