### ISSUE TITLE
Remove checking of 'version.txt'

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit#719]
The version checking in version.txt (on multibit.org) is redundant now as it has been replaced by install4j functionality. Remove.

Note that we will have to keep the version.txt file on the server updated to cater for older versions of MultiBit Classic.

**Comment by jim618** [comment]
Removed AlertManager / checking of version.txt from multibit.org server.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Code review looks fine.

Closing.
