### ISSUE TITLE
Wrong text on Send confirm screen

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit#720]
The transaction fee text is incorrectly labelled 'Transaction fee (BTC/KB)' whereas it is in fact BTC

**Comment by jim618** [comment]
Added another localisation key so that there is one term with "BTC/KB" on the preferences screen and another with "BTC" for when an actual fee is used e.g. transactionDetailsDialog.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Still seeing the old BTC/KB label in the current 0.0.0 installer.
Executing from IDE observed the correct text.
Closing since the latest code will be in the next installer edition.
