### ISSUE TITLE
Log file location incorrect

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit#726]
When the installer is used:
+ On a Mac the log file is in the app, called output.log (next to the executable jar)
+ On Windows there seems to be no sign of it.

**Comment by jim618** [comment]
This was fixed by an update to the Install4j installer (pushed) which was redirecting the log.
Also updated the main class to be MultiBitInExecutableJar (which performs the redirection).

To retest either rebuild an installer or wait until I build some and copy them to multibit.org releases dir.

Awaiting review and closing

**Comment by gary-rowe** [comment]
After using the latest installers here are the results (after a smooth installation experience):

* OS X - no sign of the log (expected to find it in Application Support/MultiBit) or in a wallet directory but nothing
* Windows - all good (located in Roaming/MultiBit/log as expected)

Bouncing back so you can you provide the OS X location.

**Comment by jim618** [comment]
for OSX it is stored as Application Support/MultiBit/log/multibit.log

Please check if you have a log directory that contains it.
This is the same as previous versions

**Comment by gary-rowe** [comment]
OK. False alarm. Turned out that I need to exercise the application more than I was doing to trigger the log write. All good now.

Closing.
