### ISSUE TITLE
Decrypted output is gobbledegook

### ISSUE THREAD

**Issue by TheButterZone** [bitcoin-solutions/multibit#728]
With my particular file paths and password, I did
openssl enc -d -p -aes-256-cbc -a -in multibit.key -out decrypted.txt -pass pass:yourpassword

a bunch of times. When I put the wrong password, I got "bad decrypt" and "error in enc" etc. Then I used what I think is the correct password, because the only lines that followed it were 
salt={letters & numbers}
key={letters & numbers}
iv ={letters & numbers}
OpenSSL>

However, when I opened the output file in a text editor, I saw not what was supposed to be there. According to https://multibit.org/en/help/v0.5/help_exportingPrivateKeys.html there should have been lines like "Labc123abc123abc123abc123abc123abc123abc123abc123abc 2013-01-01T12:00:00Z"

But instead there a bunch of symbols, letters & numbers, gobbledegook.

ETA: I subsequently ran the process on a second multibit.key file and it gave the same "success" lines as above, but actually decrypted with proper output.

**Comment by jim618** [comment]
From your extra information it sounds like the original key export file format was not quite right.
When we write the file out we then immediately read it back it to check it but of course that is no guarantee that TODAY it is ok.

As you managed to read your private keys successfully I will close this issue.

One of our motivations for writing MultiBit HD was that keeping safe 12 words is much easier than binary file formats.

**Comment by TheButterZone** [comment]
The second multibit.key file I processed, that actually decrypted with proper output, was created months before (8-10-12) the one that decrypted to gobbledegook (3-11-13). Why would OSX and/or Multibit suddenly corrupt the binary?
