### ISSUE TITLE
multibit.wallet will not sync 0.5.18

### ISSUE THREAD

**Issue by CleaverUK** [bitcoin-solutions/multibit#733]
Hi guys,

So i generated alot of wallet addresses back at the end of 2014 in October / November time but now when I turn on multibit it fails to sync...

I was a bit careless and sent some coins to one of my addresses before making sure it sync'd first and now I cant move the coins (or even see them) 

I tried 'reset blockchain and transactions' and it always stalls about the same point

![here](http://my.jetscreenshot.com/demo/20151015-mut1-225kb.jpg)

before it freezes its slows right down. I thought maybe because I have so many keys it is just taking ages. it slows down at the time I generated the keys so presumably that because after this date it actually needs to start checking what coins belong to me? 

I tried exporting them and then into blockchain.info but it says my password is incorrect which is not true. Bad security practice but its a very simple 1 word password. I only use this wallet for temp storage so it hardly holds coins more than a few hours. 

I have opened port 8333 in/out tcp and udp on my router and turned off my software firewall to rule that out (although it has always synced fine in the past with software firewall and just uPnP on the router)

I have pulled a backup out of C:\Users\<username>\AppData\Roaming\MultiBit\multibit-data\wallet-backup, pasted it into C:\Users\<username>\AppData\Roaming\MultiBit and renamed to multibit.info and multibit.wallet respectively and letting it sync but it keeps stalling and feels like its taking forever.

I dont think I have been hacked because the coins are still sitting in the wallet I have sent them too for over 12 hours, logical reasoning says to me anyone smart enough to design malware to steal bitcoin wouldnt leave it in that address for so long..... or maybe they have the wallet file, somehow corrupted mine and are now trying to brute force the pw which might take a few days because its a 12 character word but a dictionary attack would crack it very quickly. 

What do you guys think? its 0.59 BTC so not going to break the bank, tbh its more about not being beaten by this bug or whatever it is than the money for me.

**Comment by jim618** [comment]
It probably is the number of addresses - I have a wallet with 500+ addresses and it is similar.

The error in exporting/importing to blockchain.info may be because you are exporting the private keys encrypted. The blockchain.info import wants plaintext i.e. unencrypted text.
It is a checkbox on the Private KEy Export screen,
MAKE SURE YOU SECURE DELETE THE FILE AFTER IT IS USED

I suggest you go down the blockchain.info route - Classic is getting a bit slow now with big wallets.

**Comment by CleaverUK** [comment]
thanks Jim

I actually managed to recover the coins by copying the backups into the parent directory and letting it sync, it worked for about 5-6 hours then stalled, restarting it it would get through a few more months, took about 20 hours total but eventually caught up to date.

Saying that I deleted the wallet and made a new one with much less addresses :)

**Comment by jim618** [comment]
Glad you got it sorted.

Personally I think Classic is getting a bit old now so you might want to look into using a fully deterministic wallet. MultiBit HD has been out for 5 months now and is pretty stable but Electrum or Copay also work well. I use all three for various purposes.

**Comment by CleaverUK** [comment]
Thanks for the advice Jim. I have been using multibit for years just out of
habit so I think its time too look at the newer versions aswell as other
SPV wallets.

Regards,
Danny

**Comment by jim618** [comment]
Yeah Classic works fine and is pretty mature - it's just that deterministic wallets are better.

In MultiBit HD you've also got support for hardware wallets (we support Trezor and, in 0.1.4, KeepKey) which are not only safer but great fun to use.

**Comment by Carl1Leon** [comment]
conduct 1) My wallet won't even show the correct balance. 2)Then the private keys wont reflect the full bitcoin held amount. 3)Restoring the block chain might not synchronise living you in limbo. 4) You cant manufacture faulty products and then apparently walk away saying it;s time for us to move on the product will not longer be supported. 
No matter what version you might have classic or HD this should work no matter what. 

If you cant deliver and fulfill this operations you shouldn't be marketing the wallet in first place as you are putting clients money at risk. Whether its multibit, keepkey or Kenneth (Heutmaker) Hodler the product provider is liable to compensate clients if it malfunctions or if it doesnt do what it is supposed to do.

I await your urgent assistance.

**Comment by TheFireBrand** [comment]
This wallet is a word: Kak.. 

Inherited someone else's poor decision to use this headache and well.. I'm ready to call this one a loss..
