### ISSUE TITLE
Transaction from August is still not spendable in multibit

### ISSUE THREAD

**Issue by fisherman85** [bitcoin-solutions/multibit#738]
This transaction is still not spendable in my multibit wallet and I don't know why.

https://www.smartbit.com.au/tx/d3e926e2a49437526ad1914abef1c4ae99450fd27276dfa173dc91627705b923

https://blockchain.info/tx-index/d3e926e2a49437526ad1914abef1c4ae99450fd27276dfa173dc91627705b923

**Comment by jim618** [comment]
That transaction looks buried under blocks so:
+ make sure you are on the latest version of MultiBit Classic (should be v 0.5.19)
+ do a Tools | Reset blockchain and transactions to resync to the network
+ it'll take a while as you look like you have an old wallet but just leave it to do its thing.

**Comment by fisherman85** [comment]
Thank you, this fixed my problem!

**Comment by jim618** [comment]
Great!
Closing.
