### ISSUE TITLE
Missing money

### ISSUE THREAD

**Issue by cyberatt** [bitcoin-solutions/multibit#740]
Hey Jim,

Windows 7
Multibit Classic 0.5.15

I sent 100USD to
 1AnAp3fTn7YpfkrWCrv92yTGKCvXhe6FFc 
from my multibit classic wallet
1G93BmtiR3FYLDqyvzt522xuuGXuAtcRfD

It went to the white square with one peer seeing the transaction. I checked on blockchain and there was nothing found so I followed the instructions of the website and reset the block chain. Result, 100USD dollars missing from my wallet but no record of transaction and the money is not in the other account.

Please help

**Comment by cyberatt** [comment]
Hey Gang,

So this morning I reset the entire blockchain for that wallet and guess what? Missing money now appears!

So I had previousely only reset the BC on the day of the transaction, that's the difference.

Okay all go back to what you were doing, no need to keep looking.

All the best,

**Comment by gary-rowe** [comment]
Good to know @cyberatt. Looking at your version number for MultiBit Classic you're a bit out of date - version 0.5.19 is out now and has many bug fixes, including one that would have helped in this situation.

Closing.
