### ISSUE TITLE
Transaction not displaying as confirmed in wallet, but is confirmed on blockchain

### ISSUE THREAD

**Issue by drewshaver** [bitcoin-solutions/multibit#743]
I've tried re-syncing (just closing and re-opening) the wallet a bunch of times. Not sure how to get MultiBit to recognize the transaction as confirmed.

Here is a link to the tx: https://blockchain.info/tx-index/8e1d27bf366dfea2f81d17a48e3b59cdccaa8c5f92b1794d46075a25e527f2cc

I'm using a hardware wallet (Trezor) if that could matter.

![screen shot 2015-12-15 at 5 46 41 pm](https://cloud.githubusercontent.com/assets/11730814/11829825/55923784-a354-11e5-88c6-8c4e0cc09174.png)
![screen shot 2015-12-15 at 5 46 58 pm](https://cloud.githubusercontent.com/assets/11730814/11829826/5594da7a-a354-11e5-8ec9-e62af460b91d.png)

**Comment by gary-rowe** [comment]
You've posted this on the MultiBit Classic issue list. I've re-posted it as [#830](https://github.com/bitcoin-solutions/multibit-hd/issues/830) on the MultiBit HD list for you.

Closing here.

**Comment by jim618** [comment]
Try doing a 'Tools | Repair wallet' which resyncs all the wallet transactions to the blockchain.
