### ISSUE TITLE
Bitcoin Classic

### ISSUE THREAD

**Issue by chriswheeler** [bitcoin-solutions/multibit#747]
Just so you are aware, a new Bitcoin Client is being launched with the support of a number of developers, miners and pools called 'Bitcoin Classic'. 

Discussion is taking place on Slack (invite at invite.bitcoinclassic.com) or on https://github.com/bitcoinclassic/bitcoinclassic

Might be worth posting a note on the Multibit Classic page to prevent any confusion, and/or testing Multibit's compatibility with larger block sizes.

Keep up the good work :)

**Comment by gary-rowe** [comment]
Thanks for the update - much appreciated. We'll take a look at Bitcoin Classic and make a note on the website to avoid confusion.

See [Website issue #271](https://github.com/bitcoin-solutions/multibit-website/issues/271)

**Comment by gary-rowe** [comment]
I'll close this issue since it is covered in the referenced one.
