### ISSUE TITLE
There was an error in creating a connection to the bitcoin network

### ISSUE THREAD

**Issue by bitcoinsupport** [bitcoin-solutions/multibit#749]
Hey so I can't access my bitcoin to send/receive payments. I have tried restarting the program, my pc but nothing works I just get that error in the bottom right hand corner. Someone help me please!

**Comment by jim618** [comment]
Can you confirm that you have read the help on this area, which is here:
https://multibit.org/en/help/hd0.2/verify-network.html

**Comment by jim618** [comment]
That's the MultiBit HD help but Classic uses the same port - 8333

**Comment by bitcoinsupport** [comment]
Hi there I have checked this but its not the problem. Got anything else I could try?

**Comment by bitcoinsupport** [comment]
Anyone?

**Comment by gary-rowe** [comment]
Just to clarify:

* you're using MultiBit Classic 0.5.19 
* you can connect to the network using a new wallet, but the old one never synchronizes (seems strange)
* you've checked that port 8333 is open on your machine and followed the [Wiki How instructions](http://www.wikihow.com/Open-Ports) to ensure that this is case

Can you verify that your local clock time is correct? MultiBit Classic does not have the clock detection alert that HD has and this can affect synchronization.

**Comment by bitcoinsupport** [comment]
Im using multibit HD

**Comment by gary-rowe** [comment]
OK, you've come in on the wrong issue database. The message you're seeing in the bottom right hand corner is associated with a block store that cannot be opened for some reason. Leading candidates are that it has become corrupted or perhaps somehow you have modified the security permissions so that it no longer has read/write access.

I'd suggest that you delete the local SPV blockchain file in your user directory and resync the wallet:

1. Quit MultiBit HD
2. Use the [file descriptions](https://multibit.org/en/help/hd0.2/files.html) help article to locate the `mbhd.spvchain` file on your operating system.
3. Delete this file
4. Start MultiBit HD and unlock your wallet
5. Observe a (long) resync of the wallet transactions

If you have difficulty deleting this file then it is likely that is what has been causing your problems.

**Comment by bitcoinsupport** [comment]
Found that file and deleted it. Problem is still occurring

**Comment by jim618** [comment]
It's odd that you can create a new wallet and sync but an existing one doesn't (as it's the same code running).
Perhaps download Lighthouse (https://www.vinumeris.com/lighthouse) which uses compatible wallet words as MultiBit HD and recreate your wallet in that. (You can also use BreadWallet if you have an iPhone)

**Comment by bitcoinsupport** [comment]
Anyway to find my wallet words on the multibit HD app? I didnt write them down this time :/

**Comment by jim618** [comment]
If the restore button (on the screen where you put in the words in) is greyed out then it's usually because there is a typo i.e. the words aren't valid. You can double check all your words here: https://www.docdroid.net/i5yc/electrum-2-bip39-list.pdf.html

**Comment by jim618** [comment]
You can also try a restore ON A DIFFERENT MACHINE - this will not have all your comments/ exchange rates etc but, as it'll create everything afresh, may sidestep any problems specific to your machine.

**Comment by bitcoinsupport** [comment]
Can you explain how that helps me find my words?

**Comment by jim618** [comment]
It helps you CHECK your words for typos. For interest if you wrote down 'did' rather than 'dad' you'd spot it. If you don't know your wallet words then it wouldn't help.

**Comment by bitcoinsupport** [comment]
I only have the wallet words from an older wallet so not the one thats broken :/

Anyone got any other ideas?

**Comment by jim618** [comment]
Without your wallet words your options are limited as you cannot do a restore of your cloud backups nor do a fresh restore on another copy of MultiBit HD or BIP32 compliant wallet.
Wallet words are designed for exactly a situation like this so if you can find them for the wallet in question you will able to do a recovery.

As Gary mentioned above, there is only one place in the code that gives that error message - opening the block store. Are you sure you deleted the mbhd.spvchain file in the directory of the wallet you are having problems with ? There is one file for EACH wallet you have on your machine.

**Comment by bitcoinsupport** [comment]
Fixed it. I didnt delete the file for the right wallet. Thank you so much all!

**Comment by gary-rowe** [comment]
Glad it all worked out.
