### ISSUE TITLE
Transaction not leaving the wallet

### ISSUE THREAD

**Issue by Pernie1** [bitcoin-solutions/multibit#750]
Bug report: It is showing the transaction as a "box" similar to what you describe under help.
Operating System: Windows 7 Enterprise
MultiBit Classic Version:0.5.15
Steps to replicate the problem: I was trying to transfer bitcoins from the wallet. After 24 hours the transaction was still showing as a "box". I reset the block chain and transactions to the day before and synchronised. The bitcoins did return to my account. I have then tried to make the transfer again and is getting the same "box" with "seen by 1 peer".  Any help to get? What am I missing? I have not had any problems before. 
Kind regards

**Comment by jim618** [comment]
You need to upgrade to MultiBit Classic 0.5.19. 
It's on the https://multibit.org website

Old versions of Classic attach far too low a fee for the Bitcoin network nowadays.

Once you've upgraded then do a 'Reset blockchain and transactions' again to sync to what's on the blockchain and try again.

**Comment by Pernie1** [comment]
Hallo Jim618
Thank you for your help. Did as you said and it all worked out.
Thank you
Per
