### ISSUE TITLE
Coins sent from wallet never made it to destination- reset chain - no record of coins ever being there

### ISSUE THREAD

**Issue by teepsteeps** [bitcoin-solutions/multibit#752]
Hi,

Last week i sent coins from my BTC purchasing site to my wallet. From there, i sent them to another site. Eventually realising the coins never actually made it, i checked my multi bit wallet to find the coins had left the wallet, but not landed where they should have. After resetting the chain, there were no record of the coins ever being there or being sent. I have a record on my purchasing site to prove they were 100% sent and landed in the wallet. Another thing, i can't for the life of me remember the email address i used to set up this wallet because it was so long ago. I wanted to update the version (currently running 0 5 14), but would not be able to sign in again when downloaded.

What can i do??? I'm now worried i may have lost my coins all together...

**Comment by jim618** [comment]
You are correct in thinking that you need to update your version (old versions of MultiBit add what is far too low a fee for current Bitcoin network conditions).

We don't collect email addresses so you can just download the Latest MultiBit Classic download from : 
https://multibit.org/releases.html

If you upgrade then, if you've just done a 'reset blockchain and transactions' you should be able to simply send your transaction again.

**Comment by teepsteeps** [comment]
If i download the latest version, will it update what i have, as in already have my old wallets on the new version?? Thanks

**Comment by jim618** [comment]
Duplicated in #754 so closing this one.
Please use one issue rather than creating new ones for the same issue.
