### ISSUE TITLE
Coins lost when sending from Classic to HD

### ISSUE THREAD

**Issue by JesseSCHN** [bitcoin-solutions/multibit#756]
I was trying to move coins from MB Classic on an old laptop to MB HD which has been just installed on a new replacement laptop.  After downloading MB HD on the new machine I was shown an BTC address (at this point the new wallet wizard had not popped up along with the date stamp/word string etc)  I then proceeded to transfer my coin balance on the older laptop, running MB Classic to this HD address.

When I reopened HD on the new machine the create new wallet wizard appeared along with the date stamp and word string info which I noted down, however this appears to have overwritten the original address which appeared after the initial HD install, and therefore I cannot access the coins at the initial address.

I need to know how I can get the coins transferred from this address into my new HD address.

Cheers

**Comment by jim618** [comment]
Only after the wallet create wizard runs is there a wallet (with addresses) to send to.
The addresses are generated from the wallet words.

Thus it is not clear what that initial address you refer to can be. Can you clarify please ?

**Comment by JesseSCHN** [comment]
Thanks jim, that being the case then I have clearly made a mistake somewhere during the process.  Obviously the address details that the payment went to are stored in my transaction history so can they payment be reversed by admin or do I just have to accept that they are lost and move on?

**Comment by JesseSCHN** [comment]
jim, embarrassingly I have just discovered my error.  I actually transferred them by mistake to an address generated by MC classic on my new laptop.  Both the MB classic and HD are on a usb drive and I must have opened the wrong program and copied that address.

I feel like an idiot but at least my coins are safe!  Many thanks for your help

**Comment by jim618** [comment]
Glad that you've got your bitcoin !
